import Sidebar from "@/components/Sidebar";
import Head from "next/head";
import styles from '@styles/applayout.module.sass'

export default function AppLayout({children}: any){
  return(
    <>
      <Head>
        <title>Fancy DRPC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      <div className={styles.content}>
        {children}
      </div>
    </>
  )
}